### ISSUE TITLE
How to Change color of Progress bar

### ISSUE THREAD

**Issue by AdarshRise** [HandyOrg/HandyControl#202]
I Wish to use this progress bar, but i don't know how to change the color of this, to Black but i failed to use " foreground color " when I was trying to use this style.

![image](https://user-images.githubusercontent.com/31347367/67924083-9c46c400-fbd5-11e9-9a05-6707a1bb65d0.png)

This error shows up 

![image](https://user-images.githubusercontent.com/31347367/67924105-aec0fd80-fbd5-11e9-982e-fcbfef5e134b.png)

```
System.InvalidOperationException
  HResult=0x80131509
  Message='[Unknown]' property does not point to a DependencyObject in path '(0).(1).(2)[1].(3)'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Media.Animation.Storyboard.VerifyPathIsAnimatable(PropertyPath path)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
   at System.Windows.Media.Animation.BeginStoryboard.Begin(DependencyObject targetObject, INameScope nameScope, Int64 layer)
   at System.Windows.StyleHelper.InvokeEventTriggerActions(FrameworkElement fe, FrameworkContentElement fce, Style ownerStyle, FrameworkTemplate frameworkTemplate, Int32 childIndex, RoutedEvent Event)
   at System.Windows.StyleHelper.ExecuteEventTriggerActionsOnChild(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Here is the Code I used.
```
  <ProgressBar HorizontalAlignment="Left" Foreground="Azure" Value="50" Style="{StaticResource ProgressBarPrimaryStripe}" Height="18.8" Margin="542.4,410.4,0,0" VerticalAlignment="Top" Width="211.6">
        <ProgressBar.RenderTransform>
            <TransformGroup>
                <ScaleTransform/>
                <SkewTransform/>
                <RotateTransform/>
                <TranslateTransform/>
            </TransformGroup>
        </ProgressBar.RenderTransform>
        </ProgressBar>
```

**Comment by AFei19911012** [comment]
You can try to change its resources, for example: Resources["PrimaryBrush"] = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#ff5722"));

**Comment by AdarshRise** [comment]
I want to keep it in XAML itself, I am trying to avoid .cs file for all UI for now, is there anyway to do that in XAML?

**Comment by ghost1372** [comment]
@AdarshRise  you can do like this
 ```
<ProgressBar Value="50" Style="{StaticResource ProgressBarPrimaryStripe}">
            <ProgressBar.Foreground>
                <DrawingBrush Viewport="0,0,20,32" TileMode="Tile" ViewportUnits="Absolute" Stretch="None">
                    <DrawingBrush.Transform>
                        <TransformGroup>
                            <RotateTransform Angle="20"/>
                            <TranslateTransform x:Name="MyTransform" X="0"/>
                        </TransformGroup>
                    </DrawingBrush.Transform>
                    <DrawingBrush.Drawing>
                        <GeometryDrawing>
                            <GeometryDrawing.Brush>
                                <LinearGradientBrush EndPoint="1,0" StartPoint="0,0">
                                    <GradientStop Color="Black" Offset="0"/>
                                    <GradientStop Color="Black" Offset="0.5"/>
                                    <GradientStop Color="White" Offset="0.5"/>
                                    <GradientStop Color="White" Offset="1"/>
                                </LinearGradientBrush>
                            </GeometryDrawing.Brush>
                            <GeometryDrawing.Geometry>
                                <RectangleGeometry Rect="0,0,20,32"/>
                            </GeometryDrawing.Geometry>
                        </GeometryDrawing>
                    </DrawingBrush.Drawing>
                </DrawingBrush>
            </ProgressBar.Foreground>
        </ProgressBar>
```

**Comment by NaBian** [comment]
just use these codes :
``` xml
<ProgressBar Style="{StaticResource ProgressBarPrimaryStripe}" Value="50">
    <ProgressBar.Resources>
        <Color x:Key="DarkPrimaryColor">Black</Color>
    </ProgressBar.Resources>
</ProgressBar>
```

**Comment by AdarshRise** [comment]
Can I change that White Stripe in the Progress bar as well? @NaBian ?

**Comment by AFei19911012** [comment]
The answer is above.
You can change the GradientStop Color and Offset to get what you want.

<ProgressBar Value="50" Style="{StaticResource ProgressBarPrimaryStripe}">
           <ProgressBar.Foreground>
               <DrawingBrush Viewport="0,0,20,32" TileMode="Tile" ViewportUnits="Absolute" Stretch="None">
                   <DrawingBrush.Transform>
                       <TransformGroup>
                           <RotateTransform Angle="20"/>
                           <TranslateTransform x:Name="MyTransform" X="0"/>
                       </TransformGroup>
                   </DrawingBrush.Transform>
                   <DrawingBrush.Drawing>
                       <GeometryDrawing>
                           <GeometryDrawing.Brush>
                               <LinearGradientBrush EndPoint="1,0" StartPoint="0,0">
                                   <GradientStop Color="Black" Offset="0"/>
                                   <GradientStop Color="Black" Offset="0.5"/>
                                   <GradientStop Color="Red" Offset="0.5"/>
                                   <GradientStop Color="Red" Offset="1"/>
                               </LinearGradientBrush>
                           </GeometryDrawing.Brush>
                           <GeometryDrawing.Geometry>
                               <RectangleGeometry Rect="0,0,20,32"/>
                           </GeometryDrawing.Geometry>
                       </GeometryDrawing>
                   </DrawingBrush.Drawing>
               </DrawingBrush>
           </ProgressBar.Foreground>
       </ProgressBar>

**Comment by jingsong-liu** [comment]
Similar question to this issue, I use the follow code to change the Carousel Page Button color but it didn't take effect, could you give any help ?
```xml
                <hc:Carousel AutoRun="True" >
                    <hc:Carousel.Resources>
                        <SolidColorBrush x:Key="PrimaryBrush" >
                            <SolidColorBrush.Color>Black</SolidColorBrush.Color>
                        </SolidColorBrush>
                    </hc:Carousel.Resources>
```
