### ISSUE TITLE
Changing the theme of the program causes an error in TabControl

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#227]
Hi If we open the tabcontrol and change the theme a few times we get the following error
Sometimes this error occurs once a theme is changed and sometimes it occurs a few times after theme change

`System.InvalidOperationException: ''PART_VerticalScrollBar' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.'`

This exception was originally thrown at this call stack:
```
	System.Windows.Media.Animation.Storyboard.ResolveTargetName(string, System.Windows.Markup.INameScope, System.Windows.DependencyObject)
	System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(System.Windows.Media.Animation.Clock, System.Windows.DependencyObject, System.Windows.Markup.INameScope, System.Windows.DependencyObject, string, System.Windows.PropertyPath, System.Windows.Media.Animation.HandoffBehavior, System.Collections.Specialized.HybridDictionary, long)
	System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(System.Windows.Media.Animation.Clock, System.Windows.DependencyObject, System.Windows.Markup.INameScope, System.Windows.DependencyObject, string, System.Windows.PropertyPath, System.Windows.Media.Animation.HandoffBehavior, System.Collections.Specialized.HybridDictionary, long)
	System.Windows.Media.Animation.Storyboard.BeginCommon(System.Windows.DependencyObject, System.Windows.Markup.INameScope, System.Windows.Media.Animation.HandoffBehavior, bool, long)
	System.Windows.Media.Animation.BeginStoryboard.Begin(System.Windows.DependencyObject, System.Windows.Markup.INameScope, long)
	System.Windows.Media.Animation.BeginStoryboard.Invoke(System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, System.Windows.Style, System.Windows.FrameworkTemplate, long)
	System.Windows.StyleHelper.InvokeEventTriggerActions(System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, System.Windows.Style, System.Windows.FrameworkTemplate, int, System.Windows.RoutedEvent)
	System.Windows.StyleHelper.ExecuteEventTriggerActionsOnContainer(object, System.Windows.RoutedEventArgs)
	System.Windows.RoutedEventHandlerInfo.InvokeHandler(object, System.Windows.RoutedEventArgs)
	System.Windows.EventRoute.InvokeHandlersImpl(object, System.Windows.RoutedEventArgs, bool)
```

![ex](https://user-images.githubusercontent.com/9213496/68995411-f072c900-08a2-11ea-9655-7d0017dd687e.gif)

**Comment by NaBian** [comment]
you can pull the newest hc codes and try again.

**Comment by ghost1372** [comment]
hi  @NaBian  I tried with the latest codes and the problem persists

**Comment by CodingOctocat** [comment]
@NaBian 我遇到过类似的问题，另一个可能关联的 issue(#990)

我的问题是这样触发的：
1. hc:ToggleBlock 的 UnCheckedContent/CheckedContent 分别添加用户控件（分别包含 DataGrid1、DataGrid2）
2. 程序启动时显示 UnCheckedContent，向 DataGrid1 添加数据
3. 切换到 CheckedContent，并切换主题 ---> 发生下述异常

这里存在几点奇怪的地方：
- 如果 UnCheckedContent/DataGrid1 没有添加数据，那么不会有异常
- 如果 UnCheckedContent/DataGrid1 添加了数据并且当前仍处于其视图(UnCheckedContent)，那么不会有异常
- 如果对 CheckedContent/DataGrid2 进行上述测试，那么不会发生异常

---

问题解决了，我找到了 [src/Shared/HandyControl_Shared/Themes/Styles/DataGrid.xaml](https://github.com/HandyOrg/HandyControl/blob/3e2869865d37f936b34d5639524fbc65482b43e0/src/Shared/HandyControl_Shared/Themes/Styles/DataGrid.xaml)，并拷贝样式到我的项目，我用的是 v3.5.1 版本，也就是说 nuget 的这个版本和上述链接的不一样？希望早点发布新版！

---

**补充：我拷贝了 DataGrid 样式到独立的资源字典，然后在 App.xaml 中合并资源字典，结果问题又出现了，最后想起来什么，那就是必须要在出问题的页面添加：**

```xaml
<Style BasedOn="{StaticResource DataGridBaseStyle}"
       TargetType="DataGrid" />
```

这样的话，才能正在“应用生效”，后面我删除了拷贝的 DataGrid 资源字典，一切正常，所以这可能是 WPF 的问题？

至于为什么 CheckedContent/DataGrid2 没有出现问题，是因为 DataGrid2 自身就使用了 `<DataGrid.Style BaseOn="DataGridBaseStyle">`。

---

还解决了我的另一个问题：[为什么切换主题后 DataGrid 的滚动条会重置到顶部？](https://github.com/BYJRK/DotNet-Discussions/discussions/412)

---

```ini
Source: DispatcherUnhandledException
Exception: Type: System.InvalidOperationException
Source: PresentationFramework
Message: 无法在“System.Windows.Controls.ControlTemplate”的名称范围内内找到“PART_VerticalScrollBar”名称。
StackTrace:
   at System.Windows.Media.Animation.Storyboard.ResolveTargetName(String targetName, INameScope nameScope, DependencyObject element)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
   at System.Windows.Media.Animation.BeginStoryboard.Begin(DependencyObject targetObject, INameScope nameScope, Int64 layer)
   at System.Windows.StyleHelper.InvokeActions(TriggerBase triggerBase, DependencyObject triggerContainer, TriggerActionCollection actions, Style style, FrameworkTemplate frameworkTemplate)
   at System.Windows.StyleHelper.InvokePropertyTriggerActions(TriggerBase triggerBase, DependencyObject triggerContainer, DependencyProperty changedProperty, DependencyPropertyChangedEventArgs changedArgs, Int32 sourceChildIndex, Style style, FrameworkTemplate frameworkTemplate)
   at System.Windows.StyleHelper.OnTriggerSourcePropertyInvalidated(Style ownerStyle, FrameworkTemplate frameworkTemplate, DependencyObject container, DependencyProperty dp, DependencyPropertyChangedEventArgs changedArgs, Boolean invalidateOnlyContainer, FrugalStructList`1& triggerSourceRecordFromChildIndex, FrugalMap& propertyTriggersWithActions, Int32 sourceChildIndex)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList`1 otherOrigins, DeferredElementTreeState& oldTreeState, Action`2 originChangedAction)
   at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
HResult: -2146233079
HelpLink: null
InnerException: null

```
