### ISSUE TITLE
[BUG] HandyControl Can not work in Multi Threaded UI Environment,  HandyControls do.

### ISSUE THREAD

**Issue by AlBannaTechno** [HandyOrg/HandyControl#744]
@NaBian I think you should pay attention to this issue,  and @ghost1372 you already solved it in  [HandyControls](https://github.com/ghost1372/HandyControls)

So, what is the issue,
Previously I tried to use [CircleProgressBar](https://hosseini.ninja/handycontrol/extend_controls/circleProgressBar/) from [STA Thread](https://docs.microsoft.com/en-us/dotnet/api/system.stathreadattribute?view=netframework-4.8)
but it never works, neither with [HandyControl](https://github.com/HandyOrg/HandyControl) nor  [HandyControls](https://github.com/ghost1372/HandyControls)

but I implemented my own and used it.

but now, I implemented a dynamic splash screen, with a multi-step window, so user can enter some inputs before the app starts
and at the same time, I should render and cache all `expensive` UI items, to improve the performance.

and as you know, this means I must create totally different threads and dispatchers, and this must be done separately,
because if we started a new STA thread from the first one, it will use the same Dispatcher

So the solution for this, is very common, in. Net/WPF Industry, and this by changing the start point of the system and control everything
I will explain the steps, in case you do not aware of it.

[All Code Available Here](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/master) with four branches
* [Master](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/master) : worked code without any library
* [ISSUE_HC](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/ISSUE_HC) : failed to run, related to [HandyControl](https://github.com/HandyOrg/HandyControl)
	> [see](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/blob/ce161f9c38b6b05f3be3419d5f05baccf010f1b2/WpfApp/SecondWindow.xaml#L12-L16)  : neither StaticResource/DynamicResource will works, or even default style, 
	> Note: this issue occur with [Control](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.control?view=netframework-4.8) based UI eg, [Button](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netframework-4.8), not [FrameworkElement](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement?view=netframework-4.8) based eg, [TextBlock](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock?view=netframework-4.8)
* [ISSUE_HCS](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/ISSUE_HCS) : worked 👍  related to [HandyControls](https://github.com/ghost1372/HandyControls)
	> [see](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/blob/8c9c00e98628792a2db36ade0d5f8cdf28eb06ae/WpfApp/SecondWindow.xaml#L13-L17) works with default style, and with Dynamic, `sure you can not use static resources here.`
* [ISSUE_MaterialDesignInXamlToolkit](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/ISSUE_MaterialDesignInXamlToolkit) works 👍 related to [MaterialDesignInXamlToolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit)
	> I implemented this, in case you want to check other libraries.

 
------

So let's start the steps to create multi-threaded UI `sure, you can just clone the mentioned repository and run it 🙏 `

### Create  `Program.cs` file/class with Main method with `STAThread` Attribute
```C#
  [STAThread]
  static void Main(string[] args) {
      
  }
```

### Add

```xaml
 <PropertyGroup>
    <StartupObject>WpfApp.Program</StartupObject>
  </PropertyGroup>
```
to `projectName.csproj`

or modify the `Startup object`

![2021-03-25_103051](https://user-images.githubusercontent.com/13814190/112443135-42f4ad00-8d55-11eb-8ac4-b478f7da5e79.png)

### every window you want to launch, you must launch it from STA Thread as

```C#
  [STAThread]
  static void Main(string[] args) {

    var thread = new Thread(() => {
      var window = new SecondWindow();
      window.Show();
      System.Windows.Threading.Dispatcher.Run();
    }) {
      IsBackground = true,
    };
    thread.SetApartmentState(ApartmentState.STA);
    thread.Start();
  }

```

But, be aware of 

1. the window you loaded this way, can not use any static resources from `App.xaml`, so either dynamic or nothing.
	> do not think about using multiple `App.xaml` classes by creating another one with a different name and inherit from [Application](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application?view=netframework-4.8) because you can [Only use one per AppDomain](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application?view=netframework-4.8#remarks) 
2. your Main window should be loaded into your application either implicitly [StartupUri](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.startupuri?view=netframework-4.8) or explicitly  [App_Startup](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.startup?view=netframework-4.8) [like This](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/blob/71ff03e21977a11e8c0aa70c722ebfc313e734d5/WpfApp/App.xaml.cs#L16-L21)
3. the app loop will terminate if you did not instantiate `App` and run it. `will explain in the next step` 

### Initialize your main `App`  and run it, like
```C#
 	var app = new App();
	app.InitializeComponent();
	app.Run();
```
this will start the loop.

> in case you want to use StartupUi here : `app.StartupUri = new Uri("MainWnd.xaml", UriKind.Relative);`

Be aware of, if you create the STA Thread inside the [App](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/blob/71ff03e21977a11e8c0aa70c722ebfc313e734d5/WpfApp/App.xaml.cs#L14) class, you will use the same dispatcher that will be used with the MainWindow of that class
means, you can not do parallel render, for different windows,
because of this, we modified the start point and create the **SecondWindow** outside of the [App](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/blob/71ff03e21977a11e8c0aa70c722ebfc313e734d5/WpfApp/App.xaml.cs#L14).

--------

<details>

  <summary>The produced exception </summary>
  

```log

System.InvalidOperationException
  HResult=0x80131509
  Message=The calling thread cannot access this object because a different thread owns it.
  Source=WindowsBase
  StackTrace:
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Freezable.System.Windows.ISealable.get_IsSealed()
   at System.Windows.StyleHelper.SealIfSealable(Object value)
   at System.Windows.StyleHelper.GetChildValueHelper(UncommonField`1 dataField, ItemStructList`1& valueLookupList, DependencyProperty dp, DependencyObject container, FrameworkObject child, Int32 childIndex, Boolean styleLookup, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetChildValue(UncommonField`1 dataField, DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetValueFromStyleOrTemplate(FrameworkObject fo, DependencyProperty dp, EffectiveValueEntry& entry)
   at System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   at System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   at System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.FrameworkElement.UpdateStyleProperty()
   at System.Windows.TreeWalkHelper.InvalidateStyleAndReferences(DependencyObject d, ResourcesChangeInfo info, Boolean containsTypeOfKey)
   at System.Windows.TreeWalkHelper.OnResourcesChanged(DependencyObject d, ResourcesChangeInfo info, Boolean raiseResourceChangedEvent)
   at System.Windows.TreeWalkHelper.OnResourcesChangedCallback(DependencyObject d, ResourcesChangeInfo info, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   at System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   at System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   at System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   at System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   at System.Windows.TreeWalkHelper.InvalidateOnResourcesChange(FrameworkElement fe, FrameworkContentElement fce, ResourcesChangeInfo info)
   at System.Windows.Application.<>c__DisplayClass150_0.<InvalidateResourceReferenceOnWindowCollection>b__0(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at WpfApp.Program.<>c__DisplayClass1_0.<RunSplashWindow>b__0() in C:\Users\AlBannaTechno\source\repos\HandyControlMultiUIThreads\WpfApp\Program.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

  This exception was originally thrown at this call stack:
    System.Windows.Threading.Dispatcher.VerifyAccess()
    System.Windows.Freezable.System.Windows.ISealable.IsSealed.get()
    System.Windows.StyleHelper.SealIfSealable(object)
    System.Windows.StyleHelper.GetChildValueHelper(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]>, ref MS.Utility.ItemStructList<System.Windows.ChildValueLookup>, System.Windows.DependencyProperty, System.Windows.DependencyObject, MS.Internal.FrameworkObject, int, bool, ref System.Windows.EffectiveValueEntry, out System.Windows.ValueLookupType, System.Windows.FrameworkElementFactory)
    System.Windows.StyleHelper.GetChildValue(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, int, MS.Internal.FrameworkObject, System.Windows.DependencyProperty, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, ref System.Windows.EffectiveValueEntry, out System.Windows.ValueLookupType, System.Windows.FrameworkElementFactory)
    System.Windows.StyleHelper.GetValueFromStyleOrTemplate(MS.Internal.FrameworkObject, System.Windows.DependencyProperty, ref System.Windows.EffectiveValueEntry)
    System.Windows.StyleHelper.ApplyStyleOrTemplateValue(MS.Internal.FrameworkObject, System.Windows.DependencyProperty)
    System.Windows.StyleHelper.InvalidateContainerDependents(System.Windows.DependencyObject, ref MS.Utility.FrugalStructList<System.Windows.ContainerDependent>, ref MS.Utility.FrugalStructList<System.Windows.ContainerDependent>, ref MS.Utility.FrugalStructList<System.Windows.ContainerDependent>)
    System.Windows.StyleHelper.DoStyleInvalidations(System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, System.Windows.Style, System.Windows.Style)
    System.Windows.StyleHelper.UpdateStyleCache(System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, System.Windows.Style, System.Windows.Style, ref System.Windows.Style)
    ...
    [Call Stack Truncated]
```

</details>

**Comment by NaBian** [comment]
How detailed the issue is ! nice work ! you can try the following codes:
```
var window = new SecondWindow
{
    Title = $"SecondWindow :  {index.ToString().PadLeft(2, ' ')}",
    Resources = new Theme()
};
```

**Comment by AlBannaTechno** [comment]
Thank you, your solution works.
Creating a **new Theme**, at this place will tie it to that thread, and this will prevent this issue because of no MultiThreaded Access-Violation here.

But, I am still wondering, about how [HandyControls](https://github.com/ghost1372/HandyControls) enabled access to the same theme from different threads with `DynamicResources`?

--------

### Update 1
* I tested the solution on my project `not attached repository` but it never works, because dictionary key duplication
* I tested it with the [provided repository](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/ISSUE_HC), but I notice, it only works with DynamicResources

I will try to reproduce the issues with steps, then update the repo and states here.

-----

### Update 2

the issue reproduced in https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/commit/e9b08f62a9e69e0b582eeffc04e0299b15a325e1
the issue in nutshell is the next

edit [Program.RunSplashWindow](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/blob/ce161f9c38b6b05f3be3419d5f05baccf010f1b2/WpfApp/Program.cs#L25) to be 
```C#
 private static void RunSplashWindow(int index)
        {
            var thread = new Thread(() =>
            {
                // suppose any additional async operations before init the window
		// ↓↓↓↓↓↓↓↓↓↓↓↓↓
                Thread.Sleep(500);
		// ↑↑↑↑↑↑↑↑↑↑↑↑↑↑

                var window = new SecondWindow
                {
                    Title = $"SecondWindow :  {index.ToString().PadLeft(2, ' ')}",
                    Resources = new Theme()
                };
                window.Show();
                System.Windows.Threading.Dispatcher.Run();
            })
            {
                IsBackground = true,
            };
            thread.SetApartmentState(ApartmentState.STA);
            thread.Start();
        }
```

so once any async works are executed, means, any delay, or to be obvious
**If the second window is initialized after App.Run(), everything will break**

the exception is
```
System.Windows.Markup.XamlParseException: ''Set property 'System.Windows.FrameworkElement.Style' threw an exception.' Line number '20' and line position '17'.'
Inner Exception
InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
```

in **Update 1**, I said
> I tested it with the [provided repository](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/ISSUE_HC), but I notice, it only works with DynamicResources

But I discovered it only works with dynamic resources if no delay, but with delay like I described in **Update 2**, it will never work.

Also, I should mention that @ghost1372 send a Pull Request https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/pull/1,
But I wait for his response about the usage of [CanBeAccessedAcrossThreads](https://github.com/ghost1372/HandyControls/blob/86025db132e0cf8c7760e4d0cb2bdb12397a18ad/src/Shared/HandyControl_Shared/HandyControls/ThemeManager/ThemeResources.cs#L85) [here](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/pull/1/files#diff-0acbe82e9a5ebc1c64bb2b8ad1cd7d974055cdaa85b89c86f13cf2d4f00aa2d2R11) since I tested it with StaticResources and it did not works

But I must mentioned that either I used `<hc:ThemeResources CanBeAccessedAcrossThreads="True"/>` or `<hc:ThemeResources CanBeAccessedAcrossThreads="False"/>`
[HandControls](https://github.com/ghost1372/HandyControls) will always work as long as I use [DynamicResource](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dynamicresource-markup-extension?view=netframeworkdesktop-4.8)
even with the second window initialized after the app was run, [see](https://github.com/AlBannaTechno/HandyControlMultiUIThreads_ISSUE/tree/bad32cac71cd084a2daa04ca50c827dd434c813f)
Which is very impressive 🥇

**Comment by ghost1372** [comment]
Check [here ](https://github.com/Kinnara/ModernWpf/pull/90/files) and [here](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/threading-model?view=netframeworkdesktop-4.8#multiple-windows-multiple-threads)
