### ISSUE TITLE
Exception:  调用的目标发生了异常。 [Growl Global Message] 

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyControl#793]
触发条件：

- 程序有窗口在消息通知的下面；
- 将鼠标移动到消息通知上，会触发无法捕捉的异常。

参考：https://getquicker.net/QA/Question/3205

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=调用的目标发生了异常。
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Windows.Interop.HwndMouseInputProvider.HasCustomChrome(HwndSource hwndSource, RECT& rcClient)
   at System.Windows.Interop.HwndMouseInputProvider.GetEffectiveClientRect(IntPtr hwnd)
   at System.Windows.Interop.HwndMouseInputProvider.PossiblyDeactivate(IntPtr hwndCapture, Boolean stillActiveIfOverSelf)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at HandyControlDemo.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Win32Exception: 0x80070578
```

https://user-images.githubusercontent.com/1972649/114879561-e22c3200-9e33-11eb-8058-83e48c32334f.mp4

**Comment by cuiliang** [comment]
Another demo.

https://user-images.githubusercontent.com/1972649/114881809-ec4f3000-9e35-11eb-8b04-19e06fb2d56e.mp4

```c#
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using HandyControl.Controls;
using Window = System.Windows.Window;

namespace WpfApp2
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void BtnTest_OnClick(object sender, RoutedEventArgs e)
        {
            Growl.InfoGlobal("文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功！");
        }
    }
}

```

**Comment by NaBian** [comment]
可以提供更多的源码吗，或者可以直接提供 zip 包，因为我这里无法复现问题

**Comment by cuiliang** [comment]
@NaBian 第一个是官方demo。 
第二个刚新建了一个项目。
[WpfApp3.zip](https://github.com/HandyOrg/HandyControl/files/6318775/WpfApp3.zip)

**Comment by cuiliang** [comment]
另外，新建的项目如果没有添加MergedDictionaries，运行的时候会直接报错。
```c#
Growl.InfoGlobal("文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功文件保存成功！");
```
https://user-images.githubusercontent.com/1972649/114887593-2c64e180-9e3b-11eb-8305-8210fe99e121.mp4

**Comment by cuiliang** [comment]
使用这里的方法解决了。
https://support.microsoft.com/en-us/topic/february-9-2021-kb4601054-cumulative-update-for-net-framework-4-8-for-windows-10-version-1803-4b87ba1b-ed9d-c5a4-3928-cdda50c54d00

在程序的app.config里添加
`<AppContextSwitchOverrides value="Switch.System.Windows.Interop.MouseInput.OptOutOfMoveToChromedWindowFix=true; Switch.System.Windows.Interop.MouseInput.DoNotOptOutOfMoveToChromedWindowFix=true " />`

例子：
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
    </startup>
	<runtime>
		<AppContextSwitchOverrides value="Switch.System.Windows.Interop.MouseInput.OptOutOfMoveToChromedWindowFix=true; Switch.System.Windows.Interop.MouseInput.DoNotOptOutOfMoveToChromedWindowFix=true " />
	</runtime>
</configuration>
```

**Comment by imba-tjd** [comment]
I met similar issue, either when upgrading HandyControl from 2.9 to 3.2, or upgrading .net framework form 4.6 to 4.7.
The Switch works, but not fully works. Clicking close button has no effect. So I changed some to warning so that the info would disappear automatically.

See https://github.com/hanmin0822/MisakaTranslator/issues/165 if you are interested.

**Comment by ZGGSONG** [comment]
需求：当最小化窗体时，如果某个服务未连接成功，则通过Global Growl弹出通知报警
错误：当应用程序最小化时，这个时候关闭Growl会导致应用程序中断

向App.config添加代码后即解决此问题，感谢感谢
```
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.Windows.Interop.MouseInput.OptOutOfMoveToChromedWindowFix=true; Switch.System.Windows.Interop.MouseInput.DoNotOptOutOfMoveToChromedWindowFix=true " />
  </runtime>
```

**Comment by jcafranca** [comment]
> ```
> <AppContextSwitchOverrides value="Switch.System.Windows.Interop.MouseInput.OptOutOfMoveToChromedWindowFix=true; Switch.System.Windows.Interop.MouseInput.DoNotOptOutOfMoveToChromedWindowFix=true " />
> ```

Thanks
